apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-admin-travel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-admin-travel-service
  template:
    metadata:
      labels:
        app: ts-admin-travel-service
    spec:
      containers:
      - command:
        - java
        - -Xmx1536M
        - -jar
        - /app/ts-admin-travel-service-1.0.jar
        image: APP_IMG
        imagePullPolicy: Always
        name: ts-admin-travel-service
        ports:
        - containerPort: 16114
        readinessProbe:
          initialDelaySeconds: 160
          periodSeconds: 10
          tcpSocket:
            port: 16114
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 160Mi
