apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-consign-price-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-consign-price-mongo
  template:
    metadata:
      labels:
        app: ts-consign-price-mongo
    spec:
      containers:
      - image: mongo:4.4.6
        imagePullPolicy: IfNotPresent
        name: ts-consign-price-mongo
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
